Jdp190303 15
interceptor2048/project-jdp-1903-03 pull request #10
Opened 2019-03-29 15:59 UTC by karolpolikarp

Added User entity and dto package

2019-03-29 16:28 UTC, interceptor2048 requested changes

2019-03-29 16:28 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "user_id")
zmień nazwę kolumnny na `id`

2019-03-29 16:48 UTC, karolpolikarp commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "user_id")
Zmienione oraz zmergowane z masterem

2019-03-30 05:30 UTC, interceptor2048 commented
Jeszcze prośba o testy klasy User.

2019-03-30 15:55 UTC, karolpolikarp commented
Dodałem testy jednostkowe

2019-03-30 16:11 UTC, karolpolikarp commented
<img width="729" alt="Zrzut ekranu 2019-03-30 o 17 10 41" src="https://user-images.githubusercontent.com/40580142/55278610-d8980600-530e-11e9-8a1b-a57fdb29ccdf.png">
usunąć @NotNull?

2019-03-30 16:19 UTC, interceptor2048 requested changes

2019-03-30 16:19 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "useridkey")
Najpierw pola, potem metody (kolejność w klasie). Konstruktory powinny być dwa argumentowe - z id oraz bez id

2019-03-30 16:19 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/domain/dto/UserDto.java
> +public class UserDto {
@AllArgsConstructor, @NoArgsConstructor - ten który dodałeś nie powinien tu być

2019-03-30 16:19 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "useridkey")
Konstruktory zrób adnotacjami.
Przy trzech polach (poza id) daj `final` - wtedy możesz użyć adnotacji do zrobienia konstruktora na polach wymaganych.

2019-03-30 18:21 UTC, karolpolikarp commented
Applying review, correcting code smells across project

2019-03-31 05:57 UTC, interceptor2048 approved these changes

2019-03-31 05:57 UTC, merged