JDP190303-33 Modification ProductMapper
interceptor2048/project-jdp-1903-03 pull request #20
Opened 2019-04-09 20:50 UTC by rbarcik

2019-04-10 20:22 UTC, fmatusiak reviewed
Hej hej,
Dla mnie kod wyglada w porzadku ale 
Widzę , że w productMapper są dwie metody createCart i createGroup i tak mysle,że to nie są odpowiednie nazwy ,ponieważ one sprawdzaja czy jest dostepny obiekt w bazie o podanym id . Moze bardziej cos pokroju nazwy: " checkIdCart, checkIdGroup " i to tyle z moich przemyslen . Pozdrawiam

2019-04-11 06:21 UTC, interceptor2048 requested changes
Daj te prywatne metody niżej - najpierw powinny być publiczne - jak wchodzę do klasy to powinienem widzieć, co ona mi oferuje, a dopiero potem jak to jest zrobione.

2019-04-11 15:24 UTC, karolpolikarp approved these changes
Moim zdaniem dobrze wykonana zmiana zaproponowana przez @interceptor2048, czyli zamiana miejscami metod prywatnych i publicznych.
Widzę, że metody create[X] i getIdFrom[X] się różnią, ale zastanowiłbym się jak inaczej te pierwsze nazwać, żeby ich zrozumienie było bardziej intuicyjne (to o czym pisał Filip).

2019-04-11 16:08 UTC, karolpolikarp approved these changes

2019-04-11 16:19 UTC, fmatusiak approved these changes
Dla mnie ok

2019-04-11 19:50 UTC, interceptor2048 approved these changes

2019-04-11 19:50 UTC, merged