JDP190303-4
interceptor2048/project-jdp-1903-03 pull request #9
Opened 2019-03-29 15:54 UTC by jerryzerek

2019-03-29 16:27 UTC, interceptor2048 requested changes

2019-03-29 16:27 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getOrders")
@GetMapping (w kolejnych też)

2019-03-29 16:27 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +
Niepotrzbna linia

2019-03-29 16:27 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +
Niepotrzebna linia

2019-03-29 16:27 UTC, interceptor2048 commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +
Niepotrzebna linia

2019-03-29 17:56 UTC, jerryzerek commented on src/main/java/com/kodilla/ecommercee/controller/OrderController.java
> +    @RequestMapping(method = RequestMethod.GET, value = "getOrders")
poprawiono

2019-03-29 17:56 UTC, jerryzerek commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +
poprawiłem

2019-03-29 17:56 UTC, jerryzerek commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +
poprawiłem

2019-03-29 17:56 UTC, jerryzerek commented on src/main/java/com/kodilla/ecommercee/domain/OrderDto.java
> +
poprawiłem

2019-03-30 05:31 UTC, interceptor2048 approved these changes

2019-03-30 05:31 UTC, merged